### ISSUE TITLE
Default value of `timeout` in RequestOptions should be Optional.empty(), not null

### ISSUE THREAD

**Issue by williamliu52** [merge-api/merge-java-client#45]
I'm testing the SDK in my Kotlin project, like so
```kotlin
val result = mergeApiClient.hris().employees().list(
      EmployeesListRequest.builder().build(),
      RequestOptions.builder()
        .accountToken("token-here")
        .build()
    )
```
When I run this, I encounter the following error
```
java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because the return value of "com.merge.api.core.RequestOptions.getTimeout()" is null
	at com.merge.api.resources.hris.employees.EmployeesClient.list(EmployeesClient.java:183)
```
I believe that this can be fixed if the [default value for `timeout` in `RequestOptions`](https://github.com/merge-api/merge-java-client/blob/main/src/main/java/com/merge/api/core/RequestOptions.java#L55) is changed from `null` to `Optional.empty()`

**Comment by dsinghvi** [comment]
@williamliu52 this should be fixed on the latest java sdk. Linking the relevant [source](https://github.com/merge-api/merge-java-client/blob/main/src/main/java/com/merge/api/core/RequestOptions.java#L55) as well. 

Apologies for the delay!
