### ISSUE TITLE
Creating Candidate with Required "applications"

### ISSUE THREAD

**Issue by prowave** [merge-api/merge-java-client#57]
I have tried to create candidates in BambooHR and Workable which both require `applications` since the Candidate is required to be associated to a Job to be created.  What is the proper way to call `apiClient.ats().candidates().create()` when a job ID is required under the `applications` attribute?

The `CandidateRequestApplicationsItem` only accepts an `Application` or `String`.

<img width="632" alt="IntelliJ IDEA 2024-07-29 23 28 55" src="https://github.com/user-attachments/assets/9f0fb3e1-9346-498b-b0d4-2614b906ef30">

Merge support says I need to pass:

```
...,
"applications": [
{
"job": "167452f2-2325-4790-b616-851ad02f4f31"
}
]
...
```

Which is not possible with the current SDK.

Using the actual `of(Application application)` produces this and returns a 400.

```
"applications": [
      {
        "job": {
          "id": "fbef24a7-c32b-4aa4-a25b-e92604048b5c"
        }
      }
]
```

**Comment by dsinghvi** [comment]
@prowave do you mind linking the code that you are using to build up the application? 

I would have expected something along the lines of: 
```java
CandidateRequestApplicationsItem.of(Application.builder()
  .job(Job.builder()
    .id("fbef24a7-c32b-4aa4-a25b-e92604048b5c")
    .build())
  .build());
```

**Comment by prowave** [comment]
@dsinghvi Here is the code that works with the SDK method signatures.  Thanks.

```
      var jobToApply = Job.builder().id("167452f2-2325-4790-b616-851ad02f4f31").build();

      var application = Application.builder().job(ApplicationJob.of(jobToApply)).build();

      var applications = List.of(Optional.of(CandidateRequestApplicationsItem.of(application)));

      var candidate = CandidateRequest.builder().firstName("Roger").lastName("Waters") //
          .emailAddresses(List.of(EmailAddressRequest.builder().value("roger@pinkfloyd.com").build())) //
          .applications(applications) //
          .build();

      var response = apiClient.ats().candidates()
          .create(CandidateEndpointRequest.builder().model(candidate).remoteUserId(remoteId).build());
```

**Comment by prowave** [comment]
It looks like in the legacy SDK, the `job` attribute was a `UUID`, and in the new SDK its a `Job`.

Deprecated SDK
```
@JsonIgnoreProperties(ignoreUnknown = true)
data class Application (

    @field:JsonProperty("id")
    val id: java.util.UUID? = null,

    /* The third-party API ID of the matching object. */
    @field:JsonProperty("remote_id")
    val remoteId: kotlin.String? = null,

    /* The candidate applying. */
    @field:JsonProperty("candidate")
    val candidate: java.util.UUID? = null,

    /* The job being applied for. */
    @field:JsonProperty("job")
    val job: java.util.UUID? = null,
```

New SDK:

```
private final Optional<ApplicationJob> job;
```

Seems like the endpoints are still expecting the payload types from the legacy SDK.


Should I be using that old one until the server-side supports the new types?

**Comment by dsinghvi** [comment]
@prowave can you try the following code snippet

```java

        var application = Application.builder().job(ApplicationJob.of("167452f2-2325-4790-b616-851ad02f4f31")).build();

        var applications = List.of(Optional.of(CandidateRequestApplicationsItem.of(application)));

        var candidate = CandidateRequest.builder().firstName("Roger").lastName("Waters") //
                .emailAddresses(List.of(EmailAddressRequest.builder().value("roger@pinkfloyd.com").build())) //
                .applications(applications) //
                .build();

        var response = apiClient.ats().candidates()
                .create(CandidateEndpointRequest.builder().model(candidate).remoteUserId("...").build());
```

**Note**: In the example above we are not creating a Job but doing `ApplicationJob.of("167452f2-2325-4790-b616-851ad02f4f31")` directly.

**Comment by dsinghvi** [comment]
This is now resolved!
